export const TEAM_MEMBERS = [
  { id: 'alice', name: 'Alice Chen', role: 'Frontend Lead', initials: 'AC', color: '#7C3AED', githubId: '', tasksCompleted: 3, tasksInProgress: 1 },
  { id: 'bob', name: 'Bob Smith', role: 'Backend Engineer', initials: 'BS', color: '#3B82F6', githubId: 'bobsmith', tasksCompleted: 1, tasksInProgress: 0 },
  { id: 'carol', name: 'Carol Davis', role: 'Full Stack Dev', initials: 'CD', color: '#10B981', githubId: '', tasksCompleted: 2, tasksInProgress: 1 },
  { id: 'dave', name: 'Dave Wilson', role: 'DevOps Engineer', initials: 'DW', color: '#F59E0B', githubId: '', tasksCompleted: 0, tasksInProgress: 1 },
  { id: 'eve', name: 'Eve Martin', role: 'UI/UX Designer', initials: 'EM', color: '#EC4899', githubId: 'evemartin', tasksCompleted: 2, tasksInProgress: 2 },
  { id: 'frank', name: 'Frank Lee', role: 'QA Engineer', initials: 'FL', color: '#06B6D4', githubId: '', tasksCompleted: 1, tasksInProgress: 0 },
];

export const MOCK_DATA = {
  columns: [
    { id: 'col-backlog', title: 'Backlog', taskIds: ['task-1', 'task-2'] },
    { id: 'col-todo', title: 'To Do', taskIds: ['task-3'] },
    { id: 'col-in-progress', title: 'In Progress', taskIds: ['task-4'] },
    { id: 'col-review', title: 'Review', taskIds: ['task-5'] },
    { id: 'col-done', title: 'Done', taskIds: ['task-6'] },
  ],
  tasks: {
    'task-1': {
      id: 'task-1',
      title: 'Design landing page mockup',
      description: 'Create high-fidelity landing page designs and component style guides using CSS tokens.',
      assignee: 'alice',
      dueDate: '2026-08-15',
      priority: 'high',
      status: 'backlog',
      subtasks: [
        { id: 'sub-1', text: 'Draft wireframes', completed: true },
        { id: 'sub-2', text: 'Select typography and colors', completed: false },
      ],
    },
    'task-2': {
      id: 'task-2',
      title: 'Evaluate API options',
      description: 'Perform performance benchmarking between REST endpoints and GraphQL queries.',
      assignee: 'bob',
      dueDate: '2026-08-20',
      priority: 'low',
      status: 'backlog',
      subtasks: [],
    },
    'task-3': {
      id: 'task-3',
      title: 'Configure CI/CD workflow',
      description: 'Configure GitHub Actions runner to build the app and trigger automated linting.',
      assignee: 'carol',
      dueDate: '2026-07-25',
      priority: 'medium',
      status: 'todo',
      subtasks: [
        { id: 'sub-3', text: 'Write build scripts', completed: false },
      ],
    },
    'task-4': {
      id: 'task-4',
      title: 'Implement auth cookies',
      description: 'Set up HTTP-only secure cookie storage for access and refresh JWTs.',
      assignee: 'alice',
      dueDate: '2026-07-20',
      priority: 'high',
      status: 'in-progress',
      subtasks: [
        { id: 'sub-4', text: 'Implement login validation', completed: true },
        { id: 'sub-5', text: 'Write auth middleware', completed: true },
      ],
    },
    'task-5': {
      id: 'task-5',
      title: 'Review billing integration PR',
      description: 'Thoroughly review the Stripe webhook handling code and verify error alerts.',
      assignee: 'dave',
      dueDate: '2026-07-18',
      priority: 'medium',
      status: 'review',
      subtasks: [],
    },
    'task-6': {
      id: 'task-6',
      title: 'Cover utility functions with tests',
      description: 'Verify string manipulators, date parsers, and custom math helper coverages reach 90%.',
      assignee: 'carol',
      dueDate: '2026-07-10',
      priority: 'low',
      status: 'done',
      subtasks: [
        { id: 'sub-6', text: 'Write parser tests', completed: true },
        { id: 'sub-7', text: 'Verify mock suite metrics', completed: true },
      ],
    },
  },
  members: {
    alice: { name: 'Alice Chen', color: '#7C3AED' },
    bob: { name: 'Bob Smith', color: '#3B82F6' },
    carol: { name: 'Carol Davis', color: '#10B981' },
    dave: { name: 'Dave Wilson', color: '#F59E0B' },
  },
  activityLog: [
    { timestamp: '2026-07-15T09:30:00', user: 'Alice Chen', action: "moved 'Implement auth cookies' to In Progress", type: 'moved' },
    { timestamp: '2026-07-15T08:15:00', user: 'Carol Davis', action: "created 'Configure CI/CD workflow'", type: 'created' },
    { timestamp: '2026-07-14T16:45:00', user: 'Bob Smith', action: "updated deadline on 'Evaluate API options'", type: 'edited' },
  ],
};
